// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clube do Contos - Histórias Reais de Brasileiros",
  description: "Descubra contos exclusivos, confissões anônimas e participe de dinâmicas valendo prêmios e Pix. Uma experiência de prazer em comunidade.",
  keywords: "contos, histórias reais, brasileiros, comunidade, telegram, contos eróticos",
  authors: [{ name: "Clube do Contos" }],
  openGraph: {
    title: "Clube do Contos - Histórias Reais de Brasileiros",
    description: "Descubra contos exclusivos, confissões anônimas e participe de dinâmicas valendo prêmios e Pix.",
    type: "website",
    locale: "pt_BR",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
        style={{ 
          scrollBehavior: 'smooth',
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale'
        }}
      >
        {children}
      </body>
    </html>
  );
}